### PR TITLE
Basic compilation with olm library

### LINKED ISSUE #2: Basic compilation with Olm library
First step in implementing a wrapper for Olm.

### PR DESCRIPTION
**Pull request by fancycade**
Edit: Closes #2. 

Implements the version function w/ test

Includes c wrapper + Makefile

Instruct on how to install olm with Debian

Typically C libraries are installed using the OS package manager. This way it pushes the complexity onto the distro instead of the library. maintainers. IMO we can remove the git submodule. I haven't done so, maybe there is something I'm missing.

Also, I have olm/megolm commented out. Unsure if this is a debian specific problem or not. Will keep working on this.

### CODE REVIEW

**Comment by fancycade** [comment]
> Also, I have olm/megolm commented out. Unsure if this is a debian specific problem or not. Will keep working on this.
According to this implementation:
https://gitlab.matrix.org/matrix-org/olm/-/blob/master/python/olm_build.py

That include might not be necessary but there are some others I missed.

**Comment by niklaslong** [comment]
Thanks for getting this started 🎉 

I've added a few changes to the project structure and got it to work on Darwin. The main difference was the location of `ERL_ROOT`.

I'm happy to use the OS package manager installation for now, though we should be cautious about versioning.

Edit: a lot of wrapper implementations seem to be using git submodules, let's keep it in the repo for now and see how we progress.

**Comment by niklaslong** [comment]
@fancycade does the  updated config still work for you locally (I'm assuming you're on Linux?)

**Comment by fancycade** [comment]
> @fancycade does the updated config still work for you locally (I'm assuming you're on Linux?)

Pulled latest version and it still works.

**Review by niklaslong — APPROVED** [review]

**Comment by niklaslong** [comment]
@fancycade This is good to go from my point of view—thoughts?

**Comment by fancycade** [comment]
@niklaslong Yep! It is ready to merge. I don't have permissions for this repo.

**Pull request merged**
